server:
    port: 8090

spring:
    datasource:
        url: jdbc:postgresql://localhost:${configurations.port}/${configurations.database}
        driver-class-name: org.postgresql.Driver
        username: ${configurations.username}
        password: ${configurations.password}
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    liquibase:
        change-log: db/changeLog.xml
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        open-in-view: false

api:
    key: 7044406eb5ff4f0791cf0975ca39a5d1
    kzt: https://api.twelvedata.com/time_series?symbol=USD/KZT&interval=1day&outputsize=12&apikey=${api.key}
    rub: https://api.twelvedata.com/time_series?symbol=USD/RUB&interval=1day&outputsize=12&apikey=${api.key}

configurations:
    port: 5433
    database: solva
    username: solva
    password: solva